build: :green_heart: updated dockerfile settings

diff --git a/docker/production/Dockerfile b/docker/production/Dockerfile
--- a/docker/production/Dockerfile
+++ b/docker/production/Dockerfile
@@ -1,24 +1,44 @@
-###############################
-#    BUILD FOR PRODUCTION     #
-###############################
-FROM node:18-alpine as production
-WORKDIR /usr/src/app
+FROM node:18-alpine AS base
+
+#DEPENDENCIES
+FROM base AS dependencies
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+#BUILDER
+FROM base AS builder
+WORKDIR /app
+COPY --from=dependencies /app/node_modules ./node_modules
+COPY . .
+
+RUN yarn build
+RUN yarn next export
+
+# PRODUCTION
+FROM base AS production
+WORKDIR /app
+
+ENV NODE_ENV production
+RUN yarn global add serve
 
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
-ENV PORT 3000
 
-COPY --chown=nextjs:nextjs package.json .
-COPY --chown=nextjs:nextjs yarn.lock .
-
-RUN yarn install --no-cache --ignore-platform
-
-COPY --chown=nextjs:nextjs . .
-
-RUN yarn build
+COPY --from=builder --chown=nextjs:nodejs /app/out/. ./app/.
 
 USER nextjs
 
 EXPOSE 3000
 
-CMD ["node", "server.js"]
+ENV PORT 3000
+
+CMD ["npx", "serve", "app"]
